services:
  valkey:
    container_name: valkey
    image: valkey/valkey:latest

  postgres:
    container_name: postgres
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
      target: final
    container_name: transit-pulse_backend
    image: transit-pulse/backend:latest
    environment:
      APP_ENV: production
      DATABASE_URL: postgres://user:pass@postgres:5432/dev?sslmode=disable
      VALKEY_URL: valkey:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
      target: final
    container_name: transit-pulse_frontend
    image: transit-pulse/frontend:latest
    ports:
      - 8080:80
