FROM golang:1.26-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download -x

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -o /app/transit \
    ./cmd/web

FROM alpine:latest AS final

WORKDIR /app

RUN addgroup -g 1000 -S transit && \
    adduser -u 1000 -S transit -G transit

COPY --from=builder /app/transit /app/transit

RUN chown -R transit:transit /app

USER transit

EXPOSE :8888
ENTRYPOINT ["/app/transit"]
